version: '3.8'

services:
  bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: utiputi
      POSTGRES_DB: users_database
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    ports:
      - "5432:5432"
