version: '3.8'

services:
  bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: utiputi
      POSTGRES_DB: users_database
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
